server:
  port: 9000
spring:
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:user_db}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  jackson:
#    default-property-inclusion: NON_NULL

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
  instance:
    preferIpAddress: true
    
#jwt:
#  secret: secretKey
#  token:
#     validity: 600000000
#  
#
##secret key - should be encrypted
#jwt.secret=secretkey
##3 minutes validity
#jwt.token.validity=180000
###ignore null fields in json
#spring.jackson.default-property-inclusion=NON_NULL